### ISSUE TITLE
Missing button to sign/send/view spend transaction?

### ISSUE THREAD

**Issue by ricochet1k** [ValleZ/Paper-Wallet#29]
There is a spend section at the bottom of the app, but all I see is Paste..., Scan... buttons with their fields. There doesn't seem to be any way to transmit the transaction. I see code for sending it with a browser, but the button to do that seems to be missing.

Also, I'd like to use this on a completely offline phone, can you add a way to view a signed transaction as a qr-code? Maybe using the URL you'd normally open in the browser?

**Comment by ValleZ** [comment]
There is nothing to send or view before it's generated. When you enter required info you will see your transaction.
