### ISSUE TITLE
Please make the app reproducible

### ISSUE THREAD

**Issue by Giszmo** [ValleZ/Paper-Wallet#42]
I was trying to reproduce the build I found on Google Play (version 3.2.0) and ran into various issues. Compilation of probably the right revision did succeed in the end but the build result differed significantly from the version on Google Play. Could you please make the app build reproducible. You can find [my full review here](https://walletscrutiny.com/posts/ru.valle.btc/) and more on [reproducible builds here](https://reproducible-builds.org/).

**Comment by ValleZ** [comment]
Do you have any specific concerns besides java ZBar library (seems I forgot to delete it, zbar is supposed to be recreated from sources)?

I use bundles to release build. https://developer.android.com/guide/app-bundle If you want match your apk you should build bundle as well and match your device with the subset of that bundle. Also it's signed by my certificate. Of course I'm not going to reveal it with same reasons why you won't to revel your private key.

Also please open the secure key generator and try to educate yourself why trusting only SecureRandom is not the best idea on Android. https://github.com/ValleZ/Paper-Wallet/blob/master/app/src/main/java/ru/valle/btc/TrulySecureRandom.java
https://bitcoin.org/en/alert/2013-08-11-android

**Comment by ValleZ** [comment]
Ah, I reverted "build Zbar from sources" because of problem with NDK on older androids. By the way, you didn't mention in the articles that there are huge *.so libraries as well. I'd afraid that more than a jar with sources ;-)

**Comment by Giszmo** [comment]
So this is the first time I encounter an App Bundle. The goal of WalletScrutiny.com is to scrutinize binary distributions and in the case of Google Play, an Android app is in the works (currently the server side doesn't work) that collects all the binaries for reproducibility checks. I want to report on all distributed binaries.

App Bundles makes things more complicated and I had not played with those yet but was expecting them to be always a stripped down version of some "complete" apk with no changes to code. Maybe res/drawable-xxhdpi missing on a low res device, maybe res/values-cn missing if not Chinese. If it gets much more complicated than that, I might have to classify all apps that use App Bundles as non-reproducible.

Would you be interested in exploring this more? You closed the issue. Is that because you don't care about reproducibility or because you assume it is reproducible now?

I revisited the app and updated [the analysis](https://walletscrutiny.com/android/ru.valle.btc/) accordingly but after having done that, I am on the one hand fairly sure that your app was indeed compiled from the code here but on the other hand there is too much of a diff to consider it reproducible. Google must use some post-processing to get from the bundle to the app that I don't see yet how to automate. I would need to extract the parameters from the Google Play app to reproduce each APK.

The "evil" .so libraries dropped out from using App Bundle as my phone is not older. Damn, that AB stuff adds complexity to my project.

**Comment by ValleZ** [comment]
Thank you for the update. In order to remove zbar library binaries
completely I have to either use zbar from Google (called Google vision API)
but it is available only in recent Android versions and for me personally
using libraries I built is more preferred than to use external version
which may contain analytics. Other option is to build it from sources what
was made in previous version and rolled back because Android NDK is not
able to build binaries for old Androids anymore. Combined with tiny 1.5k
userbase and that someone claim that they lost money like every month by
using my free app with no ads which was in fact the only other Bitcoin
implementation in Java not so long time ago and the fact that I don't
control Google build process - yes I don't care about reproducibility of
the app. If someone would like to use it seriously they should use it only
on a device which doesn't have internet access and won't ever have it while
the app is installed. And to be a bit more safe the app should be built
from sources. I keep the build process simple.

**Comment by Giszmo** [comment]
> which may contain analytics

third party library analysis for reproducibility is the elephant in the room for my project. "If Google were evil they wouldn't need to be evil via their barcode reader lib" is kind of the counter argument here but yes, those libaries better be open source and in the case of zbar I think they are but you could also use https://github.com/journeyapps/zxing-android-embedded. No NDK needed.

> tiny user base

Yes, if you don't intend to expand the app - and paper wallets are kind of dead if it means single-key-accounts, more so if no SegWit support - I get you don't want to put much into this.

> don't control Google build process

I'm scared of Google making App Bundles mandatory. So far I can resist their constant begging to activate it but what the hack? Why should Google manage the release key?

Given the tiny user base and limited scope of the project, I don't smell a MtGox 2.0 situation but I'm still curious how to resolve App Bundles in case other, more expansive apps opt into it, so thank you very much for your collaboration. It was very helpful.

**Comment by emanuelb** [comment]
Details for building this app which generate: aab file & apk-sets from it & universal apk from it, and how to compare the results to file/files downloaded from google-play are at:
https://gitlab.com/walletscrutiny/walletScrutinyCom/-/issues/277
