### ISSUE TITLE
Very old app (2.6.0) in f-droid

### ISSUE THREAD

**Issue by emanuelb** [ValleZ/Paper-Wallet#44]
The version in: https://f-droid.org/en/packages/ru.valle.btc/ is very old 2.6.0,
can you look why is it not updated? build failure in newer versions? something else?

**Comment by ValleZ** [comment]
I never uploaded anything there, you can ask fdroid support about this

**Comment by OmlineEditor** [comment]
This is your program, ask to do an automatic update so that you don't have to do anything manually. this is possible and you as the owner will be able to do it.

**Comment by ValleZ** [comment]
I never uploaded it to F-Droid.

**Comment by OmlineEditor** [comment]
Почему вы не хотите расширить круг пользователей и добавить на f-droid? В чем проблема?

**Comment by ValleZ** [comment]
Зачем? Это бесплатная программа.

**Comment by ValleZ** [comment]
А FDroid убогий как я не знаю что

**Comment by OmlineEditor** [comment]
Я знаю что FDroid очень убогий и кривой как не знаю что, что есть то есть, но это единственная нормальная альтернатива Гугл плею. Может все таки хотя бы поможете другим людям правильно компилировать из исходников вашу програму? Они ее без вас выложать, от вас только совет как вы скомпиливали ZBar из исходников.

**Comment by ValleZ** [comment]
Неа. Кому надо, сами справятся. Тем более что версия с сишными исходниками в истории GIt лежит. Но пуристам этого недостаточно будет - там много библиотек типа bouncy castle и androidx. И даже если пуристы соберут это все в исходном виде (если работают в гугле) то я зуб даю, все исходники даже один раз не посмотрят.

**Comment by OmlineEditor** [comment]
Исходникик смотрят скриптами на предмет заклядок и подозрительных мест. Так что если вы собирали раньше из исходников тогда хотябы дайте короткую иснтрукцию как это сделать, а то там кажется у них не выходит.

**Comment by ValleZ** [comment]
1.68K пользователей.

**Comment by OmlineEditor** [comment]
получается 85% поставили и потом снесли? Печально что так мало пользователей, я думала что их намного больше, но все равно довольно много пользователей. Вы планируете улучшать программу и делать ее лучше?

**Comment by ValleZ** [comment]
Нет, только поддерживаю и обновляю когда мне самому что-то требуется.

**Comment by OmlineEditor** [comment]
Ну и на том спасибо, хоть не забросили приложение уже хорошо. Жаль что обновлния будут выходить редко, т.к. приложение полностью рабочее и больше там доделывать почти нечего, кроме строки "О приложении" https://github.com/ValleZ/Paper-Wallet/issues/56
