### ISSUE TITLE
policy directory used? is zip file redundant? index.html contain broken links

### ISSUE THREAD

**Issue by emanuelb** [ValleZ/Paper-Wallet#45]
The `policy` folder contain 2 files `index.html` & `index.html.zip`: 
https://github.com/ValleZ/Paper-Wallet/blob/6f379acad6541d1f797b30cf129874ba9846586f/policy/index.html
https://github.com/ValleZ/Paper-Wallet/blob/650cda33901ba5b2f0483078a6a2d141dbe64f70/policy/index.html.zip

are 1 of the files redundent? both are needed? also the HTML itself contain broken links:
```html
<script type="text/javascript" src="//use.typekit.net/lzd2nbb.js"></script>
```
loading this resource over https result in 404 not found error: https://use.typekit.net/lzd2nbb.js

didn't find mention of this files in code-base, are they used?! they are not inside the APK of latest version 3.2.0 on google-play.

**Comment by yeru83** [comment]
When I take a look at:
https://github.com/ValleZ/Paper-Wallet/ 
I do not see any subdirectory named "blob" anymore.  

Check here, maybe some clues about libraries:
https://github.com/ValleZ/Paper-Wallet/issues/42

All the best :-)

**Comment by emanuelb** [comment]
`blob` is not a directory, it's a way for github link to point into current files, here the files now on master branch:
https://github.com/ValleZ/Paper-Wallet/blob/master/policy/index.html
https://github.com/ValleZ/Paper-Wallet/blob/master/policy/index.html.zip
The linked issues about reproducible builds don't contain information about this files ^^
clone this directory, there is `policy` directory in it, the issues is about the `index.html` & `index.html.zip` files in `policy` directory
