### ISSUE TITLE
Enable gradle dependency verification

### ISSUE THREAD

**Issue by emanuelb** [ValleZ/Paper-Wallet#48]
This is done by having `./gradle/verification-metadata.xml` file, more information:
https://docs.gradle.org/current/userguide/dependency_verification.html

**Comment by ValleZ** [comment]
This is new technology and it's too unpolished to be actually used in any mobile build. It cannot even generate all checksums for androidx.activity:activity:1.3.1 automatically. You may submit a PR which works on all platforms with clear instructions what to do when it doesn't.
