### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [ValleZ/Paper-Wallet#53]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 60  warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on Paper-Wallet (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure). 

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve Paper-Wallet's security, and the quality of the reports of static analysis tools.
(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by ValleZ** [comment]
Yes, I'd like to see your bug reports.

**Comment by misterAnderson90** [comment]
Hi @ValleZ,

I have sent you the reports by email. I'm sorry for taking so long to share this with you.

**Comment by ValleZ** [comment]
I don't see anything worth looking at, only hand waiving about generating secure random numbers. Do you have a precise description what is the problem?
