### ISSUE TITLE
update the version to f-droid

### ISSUE THREAD

**Issue by OmlineEditor** [ValleZ/Paper-Wallet#55]
your program is updated manually, not automatically on the f-droid website. update it manually

**Comment by emanuelb** [comment]
Related old issue about it: #44 This should be fixed at gitlab, related issue is: https://gitlab.com/fdroid/fdroiddata/-/issues/2006

**Comment by OmlineEditor** [comment]
do you use the ZBar `https://github.com/ZBar/ZBar` program, do you compile this program manually from source or do you add a ready-made binary file to the program?

**Comment by ValleZ** [comment]
I don't maintain FDroid and never uploaded it there,

**Comment by OmlineEditor** [comment]
Хорошо, вы не добавляли програму на F-Droid, ответьте вопрос был ли у вас использован ZBar в виде исходников или в виде готового бинарного файла?

**Comment by ValleZ** [comment]
Бинарник. Была версия с компиляцией из исходника, но это очень усложняло сборку.
