### ISSUE TITLE
add to the program settings "about the program"

### ISSUE THREAD

**Issue by OmlineEditor** [ValleZ/Paper-Wallet#56]
add "about" to the program settings to know which version I have installed now, as well as a link to your program on github. you can also get license information

**Comment by ValleZ** [comment]
You can check version in system app info. License info is available on github.

**Comment by OmlineEditor** [comment]
Are you kidding? it's not convenient.

**Comment by ValleZ** [comment]
How often do you do this?

**Comment by ValleZ** [comment]
I'll accept a PR though.

**Comment by OmlineEditor** [comment]
you only need to add three lines to the program:
- Paper-Wallet v 3.5.0
- License: The MIT License (MIT) 
- The sources are here:  https://github.com/ValleZ/Paper-Wallet

I think this is the easiest task for you.
